# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: G for Gavin
url:   http://www.gavinlin.com
author:
  name:    Gavin Lin			# For copyright notice and ATOM feeds
  email:   gavinlin@outlook.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  	# These are used to login to the admin area
      - http://gavinlinasd.myopenid.com/
      - https://profiles.google.com/100100557822078438877

